backend:
  name: github
  # change repo to your git repository url
  repo: chardmd/obscurepdfs-v2

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: data
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: pdfList }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: url, label: URL }
      - label: Featured Image
        name: image
        widget: image
        required: true
        hint: "Image size 1280x800 works best :)"
        media_library:
          config:
            multiple: false
